export default {
  m: {
    ADD_CLIP: 'ADD_CLIP',
    REMOVE_CLIP: 'REMOVE_CLIP',
    REMOVE_ALL_CLIP: 'REMOVE_ALL_CLIP',
    SELECT_CLIP: 'SELECT_CLIP',
    SWAP_CLIP_ORDER: 'SWAP_CLIP_ORDER',
    UPDATE_DELAY: 'UPDATE_DELAY',
    ADD_SVG_ELEMENT: 'ADD_SVG_ELEMENT',
    UPDATE_SVG_ELEMENT: 'UPDATE_SVG_ELEMENT',
    REMOVE_SVG_ELEMENT: 'REMOVE_SVG_ELEMENT',
    UNDO_SVG_ELEMENT: 'UNDO_SVG_ELEMENT',
    REDO_SVG_ELEMENT: 'REDO_SVG_ELEMENT',
    JUMP_SVG_ELEMENT_HISTORY: 'JUMP_SVG_ELEMENT_HISTORY'
  },
  a: {
    CREATE_CLIP: 'CREATE_CLIP',
    DELETE_CLIP: 'DELETE_CLIP',
    DELETE_ALL_CLIP: 'DELETE_ALL_CLIP',
    SELECT_CLIP: 'SELECT_CLIP',
    SWAP_CLIP_ORDER: 'SWAP_CLIP_ORDER',
    UPDATE_DELAY: 'UPDATE_DELAY',
    CLONE_CLIP: 'CLONE_CLIP',
    CREATE_SVG_ELEMENT: 'CREATE_SVG_ELEMENT',
    UPDATE_SVG_ELEMENT: 'UPDATE_SVG_ELEMENT',
    DELETE_SVG_ELEMENT: 'DELETE_SVG_ELEMENT',
    UNDO_SVG_ELEMENT: 'UNDO_SVG_ELEMENT',
    REDO_SVG_ELEMENT: 'REDO_SVG_ELEMENT',
    JUMP_SVG_ELEMENT_HISTORY: 'JUMP_SVG_ELEMENT_HISTORY'
  },
  g: {
    CLIP_LIST: 'CLIP_LIST',
    SELECTED_CLIP: 'SELECTED_CLIP',
    WHOLE_SIZE: 'WHOLE_SIZE',
    WHOLE_DELAY: 'WHOLE_DELAY'
  }
}
