export default {
  m: {
    ADD_CLIP: 'ADD_CLIP',
    REMOVE_CLIP: 'REMOVE_CLIP',
    REMOVE_ALL_CLIP: 'REMOVE_ALL_CLIP',
    SELECT_CLIP: 'SELECT_CLIP',
    SWAP_CLIP_ORDER: 'SWAP_CLIP_ORDER',
    UPDATE_DELAY: 'UPDATE_DELAY',
    SET_CANVAS_MODE: 'SET_CANVAS_MODE'
  },
  a: {
    CREATE_CLIP: 'CREATE_CLIP',
    DELETE_CLIP: 'DELETE_CLIP',
    DELETE_ALL_CLIP: 'DELETE_ALL_CLIP',
    SELECT_CLIP: 'SELECT_CLIP',
    SWAP_CLIP_ORDER: 'SWAP_CLIP_ORDER',
    UPDATE_DELAY: 'UPDATE_DELAY',
    CLONE_CLIP: 'CLONE_CLIP',
    SET_CANVAS_MODE: 'SET_CANVAS_MODE'
  },
  g: {
    CLIP_LIST: 'CLIP_LIST',
    SELECTED_CLIP: 'SELECTED_CLIP',
    WHOLE_SIZE: 'WHOLE_SIZE',
    WHOLE_DELAY: 'WHOLE_DELAY',
    CANVAS_MODE: 'CANVAS_MODE'
  }
}
